---
- name: update packages
  become: true
  apt:
    upgrade: yes
- name: install nodejs, npm and pm2
  become: true
  apt:
    name: 
      - nodejs
      - npm
    state: latest
    update_cache: yes
- name: install pm2
  become: true
  shell: npm install pm2 -g